[config]
schemaVersion = "0.0.1"

[package]
namespace = "DatUub"
description = "Quest management mod for Silksong — accept, complete, and customize quest targets with a full debug GUI."
# Bump version for dependency fix
version = "1.1.1"
websiteUrl = "https://github.com/DatUub/Silksong.QuestMod"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"
silksong_modding-DataManager = "1.2.1"
silksong_modding-FsmUtil = "0.3.13"
silksong_modding-UnityHelper = "1.1.1"

[build]
icon = "./logo.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "./temp"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong" ]

[publish.categories]
hollow-knight-silksong = [ "mods", "utility", "accessibility" ]
